name: Build and Test Spring Boot Docker Image

on:
  push:
    branches:
      - main  # Trigger the action on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger the action on pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          java-package: jdk
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Build Docker image
        run: docker build -t spring-boot-app .

      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 --name spring-boot-container spring-boot-app

      - name: Wait for app to start
        run: sleep 30  # Adjust this as needed based on your app's startup time

      - name: Run tests inside Docker container
        run: |
          docker exec spring-boot-container mvn test

      # Optionally, stop the Docker container after tests are complete
      - name: Stop Docker container
        run: docker stop spring-boot-container
