name: Build and Deploy Spring Boot Docker Image

on:
  push:
    branches:
      - main  # Trigger the action on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger the action on pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          java-package: jdk
          distribution: 'adoptopenjdk'  # Specify Java distribution

      # Build the Spring Boot application (with Maven or Gradle)
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Build Docker image
      - name: Build Docker image
        run: docker build -t your-image-name .

      # Log in to Docker Hub (if pushing to Docker Hub)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push the Docker image to Docker Hub (if applicable)
      - name: Push Docker image to Docker Hub
        run: docker push javaRun

      # Optionally, run the container (for testing or deploying)
      - name: Run Docker container
        run: docker run -d -p 8080:8080 javaRun
